# Generated by Django 4.2.7 on 2025-12-29 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("members", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deal_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "rooms",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_id", models.UUIDField(db_index=True)),
                ("text", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("system", "Системное"),
                            ("deal_proposal", "Предложение сделки"),
                            ("deal_activated", "Сделка активирована"),
                            ("deal_completion_request", "Запрос завершения"),
                            ("deal_completed", "Сделка завершена"),
                            ("deal_cancelled", "Сделка отменена"),
                        ],
                        default="text",
                        max_length=30,
                    ),
                ),
                (
                    "deal_data",
                    models.JSONField(
                        blank=True,
                        help_text="Данные сделки для интерактивной карточки",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.room",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
    ]
