# Generated by Django 4.2.7 on 2026-01-27 07:20

import apps.messaging.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_id", models.UUIDField(db_index=True)),
                ("text", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("system", "Системное"),
                            ("deal_proposal", "Предложение сделки"),
                            ("deal_activated", "Сделка активирована"),
                            ("deal_completion_request", "Запрос завершения"),
                            ("deal_completed", "Сделка завершена"),
                            ("deal_cancelled", "Сделка отменена"),
                        ],
                        default="text",
                        max_length=30,
                    ),
                ),
                (
                    "deal_data",
                    models.JSONField(
                        blank=True,
                        help_text="Данные сделки для интерактивной карточки",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("members", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deal_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "rooms",
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Файл-вложение (до 20MB)",
                        max_length=500,
                        null=True,
                        upload_to=apps.messaging.models.message_attachment_upload_path,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL файла на внешнем сервисе (например, market service)",
                        max_length=1000,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Оригинальное имя файла", max_length=255
                    ),
                ),
                ("file_size", models.IntegerField(help_text="Размер файла в байтах")),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "db_table": "message_attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.room",
            ),
        ),
    ]
