# Generated by Django 4.2.7 on 2026-02-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_add_read_receipts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_room_id_9d87cc_idx",
            old_name="messages_room_created_idx",
        ),
        migrations.RenameIndex(
            model_name="readreceipt",
            new_name="read_receip_room_id_4cb980_idx",
            old_name="read_receipts_room_user_idx",
        ),
        migrations.RenameIndex(
            model_name="room",
            new_name="rooms_updated_9554b5_idx",
            old_name="rooms_updated_idx",
        ),
    ]
