# Generated by Django 4.2.7 on 2026-01-08 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chat_room_id", models.UUIDField(db_index=True)),
                ("client_id", models.UUIDField(db_index=True)),
                ("worker_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(help_text="Техническое задание")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен, в работе"),
                            ("delivered", "Сдан на проверку"),
                            ("completed", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("revision_count", models.IntegerField(default=0)),
                ("max_revisions", models.IntegerField(default=2)),
                ("delivery_message", models.TextField(blank=True)),
                ("completion_message", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("last_message_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("held", "Захолдировано"),
                            ("captured", "Списано"),
                            ("refunded", "Возвращено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_provider", models.CharField(default="stub", max_length=50)),
                (
                    "external_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="services.deal",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("owner_id", models.UUIDField(db_index=True)),
                ("owner_name", models.CharField(blank=True, max_length=255)),
                ("owner_avatar", models.TextField(blank=True, null=True)),
                (
                    "ai_template",
                    models.TextField(
                        blank=True, help_text="Требования к клиенту (бриф)", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("development", "Разработка"),
                            ("design", "Дизайн"),
                            ("marketing", "Маркетинг"),
                            ("writing", "Копирайтинг"),
                            ("video", "Видео и анимация"),
                            ("audio", "Аудио"),
                            ("business", "Бизнес"),
                            ("other", "Другое"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "services",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="services_categor_af53e2_idx",
                    ),
                    models.Index(
                        fields=["owner_id"], name="services_owner_i_3bfcb6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField(help_text="Оценка от 1 до 5")),
                ("comment", models.TextField(blank=True)),
                (
                    "reviewer_id",
                    models.UUIDField(help_text="Кто оставил отзыв (обычно клиент)"),
                ),
                (
                    "reviewee_id",
                    models.UUIDField(help_text="О ком отзыв (обычно исполнитель)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="services.deal",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.service",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["chat_room_id", "status"], name="deals_chat_ro_b68be3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["client_id", "status"], name="deals_client__999d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["worker_id", "status"], name="deals_worker__002dd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "paid", "delivered"])),
                fields=("client_id", "worker_id"),
                name="unique_active_deal_per_pair",
            ),
        ),
    ]
