# Generated by Django 4.2.7 on 2026-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="cancelled_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="completion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="completion_requested_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="last_deal_message_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("proposed", "Предложена"),
                    ("active", "Активна"),
                    ("completion_requested", "Запрос завершения"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
