# Generated by Django 4.2.7 on 2026-01-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_is_active"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="service",
            new_name="services_is_acti_9eb22e_idx",
            old_name="services_is_active_idx",
        ),
    ]
