# Generated by Django 4.2.7 on 2026-01-28 08:28

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_rename_services_is_active_idx_services_is_acti_9eb22e_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.services.models.validate_tags],
            ),
        ),
    ]
