# Generated by Django 4.2.7 on 2026-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="subcategory",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Подкатегория услуги (опционально)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "subcategory", "-created_at"],
                name="services_categor_973d34_idx",
            ),
        ),
    ]
