# Generated by Django 4.2.7 on 2026-02-08 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_service_subcategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(db_index=True, help_text="ID пользователя"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["-price"], name="services_price_e2d79c_idx"),
        ),
        migrations.AddField(
            model_name="favorite",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="services.service",
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user_id", "-created_at"], name="favorites_user_id_f73cef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user_id", "service")},
        ),
    ]
