# Generated by Django 4.2.7 on 2026-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_medusa_integration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deal',
            name='unique_active_deal_per_pair',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('development', 'Разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('writing', 'Копирайтинг'), ('video', 'Видео и анимация'), ('audio', 'Аудио'), ('business', 'Бизнес'), ('photo', 'Фото'), ('legal', 'Юридические услуги'), ('other', 'Другое')], db_index=True, default='other', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'paid', 'delivered', 'dispute'])), fields=('client_id', 'worker_id'), name='unique_active_deal_per_pair'),
        ),
    ]
