# Generated by Django 4.2.7 on 2026-02-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_telegram_integration"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                ("successful", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "login_attempts",
                "ordering": ["-attempt_time"],
                "indexes": [
                    models.Index(
                        fields=["email", "-attempt_time"],
                        name="login_attem_email_a5aa13_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-attempt_time"],
                        name="login_attem_ip_addr_8008e5_idx",
                    ),
                ],
            },
        ),
    ]
