# Generated by Django 4.2.7 on 2026-02-04 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_email_verified_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="new_email",
            field=models.EmailField(
                blank=True, help_text="Новый email для смены", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("registration", "Подтверждение при регистрации"),
                    ("email_change", "Подтверждение смены email"),
                ],
                default="registration",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
