from django.urls import path
from .views import (
    RegisterView, 
    LoginView,
    LogoutView,
    ProfileView, 
    CheckBalanceView, 
    BatchUsersView, 
    PublicProfileView,
    SubscriptionView,
    TelegramGenerateLinkView,
    TelegramVerifyTokenView,
    TelegramDisconnectView,
    TelegramGetUserByIdView,
    CookieTokenRefreshView,
    VerifyEmailView,
    ResendVerificationView,
    UpdateEmailView,
    RequestEmailChangeView,
    ConfirmEmailChangeView,
    ForgotPasswordView,
    ResetPasswordView,
    ChangePasswordView,
    DeleteAccountView,
)
from . import views

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('token/refresh/', CookieTokenRefreshView.as_view(), name='token_refresh'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify_email'),
    path('resend-verification/', ResendVerificationView.as_view(), name='resend_verification'),
    path('update-email/', UpdateEmailView.as_view(), name='update_email'),
    path('request-email-change/', RequestEmailChangeView.as_view(), name='request_email_change'),
    path('confirm-email-change/', ConfirmEmailChangeView.as_view(), name='confirm_email_change'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('check-balance/', CheckBalanceView.as_view(), name='check_balance'),
    path('users/batch/', BatchUsersView.as_view(), name='users_batch'),
    path('users/<uuid:user_id>/', PublicProfileView.as_view(), name='public_profile'),
    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    path('internal/users/<uuid:user_id>/profile/', views.InternalUserProfileView.as_view(), name='internal-user-profile'),
    path('telegram/generate-link/', TelegramGenerateLinkView.as_view(), name='telegram_generate_link'),
    path('telegram/verify-token/', TelegramVerifyTokenView.as_view(), name='telegram_verify_token'),
    path('telegram/disconnect/', TelegramDisconnectView.as_view(), name='telegram_disconnect'),
    path('telegram/get-user/', TelegramGetUserByIdView.as_view(), name='telegram_get_user'),
]
